theme: jekyll-theme-cayman
title: Bienvenido a Mi Blog M7
description: <br>En este Blog aprenderemos a crear un dominio, instlar el Docker, configurar un certificado para el Cliente y Servidor<br>
<a href="https://github.com/Santosmoran/MiBlog/semana1/semana1.html" 
class="btn">Mi Primera Semana</a>
lang: es
google_analytics: UA-131585940-1
